name: fly_dash
description: "fly dash game"
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flame: ^1.30.0
  flame_audio: ^2.11.7
  flutter_bloc: ^9.1.1
  flame_bloc: ^1.12.13
  equatable: ^2.0.7
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:


flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    image: false


flutter:

  uses-material-design: true
  assets:
    - assets/audio/
    - assets/fonts/
    - assets/images/
    - assets/lottie/
    - assets/images/background/


  fonts:
    - family: ZCOOLKuaiLe
      fonts:
        - asset: assets/fonts/ZCOOLKuaiLe-Regular.ttf